name: Release web page
on:
  push:
    branches:
      - master

jobs:
  release_webpage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Build production web page
        run: ./gradlew wasmJsBrowserProductionWebpack

      - name: Package production web page
        run: ./gradlew wasmJsBrowserDistribution

      - name: Publish to gh-pages
        run: |
          git worktree add --detach docs-temp
          cd docs-temp
          git checkout --orphan gh-pages
          git reset HEAD -- .
          git clean -df
          mv ../build/dist/wasmJs/productionExecutable/* .
          git status
          git config --global user.email "actions@openrndr.org"
          git config --global user.name "OPENRNDR Actions"
          git add . 
          git commit -m "Add automatically generated web page"
          git push origin gh-pages --force